---
title: "Syllabus"
output:
  html_document:
    toc: yes
    toc_depth: 1
    toc_float:
      collapsed: no
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE, 
                      cache=TRUE, fig.width=16/2, fig.height=9/2)
# Set seed value of random number generator to get "replicable" random numbers.
# Why 76? Because of https://www.youtube.com/watch?v=xjJ7FheCkCU
set.seed(76)
```

<style>
h1{font-weight: 400;}
</style>

# Basic information {#basicinfo}

* **Course title:** SDS/CSC 293: Machine Learning
* **Instructor:** [Albert Y. Kim](https://rudeboybert.rbind.io/) - Assistant Professor of Statistical & Data Sciences
* **~~Email:~~ Slack team**: Click hashtag icon in navbar for the browser interface or use the [desktop app](https://slack.com/downloads/){target="_blank"}.
* **Meeting locations/times:** 
    + **Lectures**: MW 1:10-2:30 - McConnell Hall 103
* **Outside help**:
    + The `#questions` channel on Slack.
    + Spinelli Center for Quantitative Learning [Tutoring](https://www.smith.edu/qlc/tutoring.html?colStats=open#PanelStats){target="_blank"}: Sunday thru Thursday 7-9pm in Sabin-Reed 301. 
    + Albert's office hours in McConnell Hall 215: Mon & Wed 2:45-4:00 and by apppointment (click [here](https://calendar.google.com/calendar/selfsched?sstoken=UVBidEVzZlJ3a2dYfGRlZmF1bHR8NmExNDk4OGM5ZWZiYWNmOWYxYWRkZDM0NmU3ZGRmMzE){target="_blank"} to book).
    + Spinelli Center Data Counselor Vahab Khademi in Seelye 207: By [appointment](https://www.smith.edu/qlc/tutoring.html?colDataCnslr=open#PanelDataCnslr){target="_blank"}.
    

## Instructor work-life balance

* I will respond to Slack messages sent during the week within 24h. I will respond to Slack messages sent during the weekend at my own discretion.
* If possible, please only Slack me with briefer and administrative questions; I prefer having more substantive conversations in person as it takes me less energy to understand where you are at.
* I will do my best to return all grading as promptly as possible.
* I will rarely be on campus on Thursdays as this is my self-care day.



***



# How can I succeed in this class?

Ask yourself:

* **When I have questions or don't understand something:**
    + *"Am I asking questions in class?"*
    + *"Am I asking questions on Slack in `#questions`?"* Even better: *"Am I answering my peers' questions on Slack?"*
    + *"Having I been going to the Spinelli tutoring center for help on R and the tidyverse?"*
    + *"Have I been coming to office hours?"*
* **Lectures, labs, and readings:**
    + *"Am I staying on top Slack notifications sent between lectures?"* If you need help developing a notification strategy that best suits your lifestyle, please speak to me. 
    + *"Am I attending lectures consistently?"*
    + *"Am I actually running the code and studying the outputs in R during in-class exercises, or am I just going through the motions?"*
    + *"During in-class exercises, am I taking full advantage that I'm in the same place at the same time with the instructor, the lab assistants, and most importantly your peers, or am I browsing the web/texting the whole time?"*
    + *"Have I been doing the associated readings for each lecture?"*
* **Problem sets, DataCamp, and coding:**
    + *"Am I actually doing the problem sets?"*
    + *"Have I been attempting a good faith balance between to push myself during DataCamp exercises while not banging my head on the wall, or am I just taking the hints/solutions without any effort?"*



***



# Course Description & Objectives

    
* **Official course description**: On [Smith College
Course Search](https://www.smith.edu/academics/academic-program/curriculum/course-search?term=Spring+2019&dept=&instr=Albert+Y.+Kim&credits=&course_numb=293&course_keywd=&op=Submit&form_build_id=form-denY7g_Jg58ti6JEd7MQqOj4CvHwIw6awhXG9B0jLHs&form_id=campus_course_search_basic_search_form){target="_blank"}.
* **Unofficial course description**: A course on the theoretical underpinnings
of machine learning. Fundamental concepts of machine learning, such as
crossvalidation and the bias-variance tradeoff, will be viewed through both
statistical and mathematical lenses. As much of the coursework will center
around participation in [Kaggle competitions](https://www.kaggle.com/), there
will be greater emphasis on supervised learning techniques including regression,
smoothing methods, classification, and regularization/shrinkage methods. To this
end, there will be a large computational component to the course, in particular
the use of tools for data visualization, data wrangling, and data modeling.



***



# Topic Schedule and Readings {#topicschedule}

We will cover the topics below; the schedule and associated readings can be found on the [main page](index.html) of this course webpage.

1. Background
    * The modeling framework
    * The machine learning framework
    * Baby's first model: splines
    * Out-of-sample prediction, sampling vs resampling, crossvalidation
    * Bias-variance tradeoff?
1. Continuous outcome models part I
    * Multiple regression for prediction
1. Categorical outcome models AKA classification
    * Logistic regression for prediction
    * ROC curves for evaluating binary classifiers
    * k-Nearest Neighbors
    * Classification and regression trees
1. Continuous outcome models part II
    * Regularization/shrinkage methods: Ridge regression and LASSO
    * Classification and regression trees
1. Unsupervised learning (no outcome variable)
    * Principal components analysis
    * k-Means clustering
1. More methods
    * Neural nets
    * Ensemble methods: random forests

We will draw from the following sources:

1. [An Introduction to Statistical Learning with Applications in R](http://www-bcf.usc.edu/~gareth/ISL/){target="_blank"}.
1. DataCamp: an online interactive environment for learning data science currently via R and Python. On top of the DataCamp courses we'll cover this semester, you have free access to [all their courses](https://www.datacamp.com/courses/all){target="_blank"} for 6 months. 

<!--

We will use chiefly use the following available textbooks:

1. ["Happy Git and GitHub for the useR"](http://happygitwithr.com/) by Jenny Bryan.
1. ["An Introduction to Statistical Learning"](http://www-bcf.usc.edu/~gareth/ISL/) by James, Witten, Hastie, and Tibshirani. We'll refer to this as "ISLR.""
1. ["Computer Age Statistical Inference"](https://web.stanford.edu/~hastie/CASI/) by Efron and Tibshirani. We'll refer to this as "CASI."
1. ["The Elements of Statitiscal Learning"](https://web.stanford.edu/~hastie/ElemStatLearn/) by Hastie, Tibshirani, and Friedman. We'll refer to this as "ESL."

The latter three are all supplemental resources: use these if you find chalk talks and the course main page are lacking in any
regard. That being said, here is a rough hierarchy of how I much I refer to them:

1. ISLR: Most of my notes center around this text, which is targeted at undergraduates.
1. ESL: This is the graduate version of ISLR, and predates ISLR by a few years.
1. CASI: A 30,000 foot overview of the past, present, and future of statistics/data science/machine learning. We'll refer to this occationally.

-->



## Policies

* Bring your laptop, a set of headphones, colored pens/pencils, and your paper notebook to every lecture.   
* You are expected to stay until the end of lecture. If you need to leave before the end of lecture, please confirm with me first.
* Attendance will not be explicitly taken and occasional absenses are excused. However, extended absenses should be mentioned to me.
* However, you are responsible for asking your peers for what you missed. For example, makeup lectures will not be held during office hours.



***



# Evaluation

## DataCamp assignments 5% {#datacamp}

* DataCamp is meant to be low stakes-practice, so the only thing that matters for your grade is whether you complete the course. So while things like the number of hints/solutions taken don't factor into your grade, it is important to make a good faith effort to answer these questions the best you can.
* While you may do them in advance if you are curious, it is most definitely not required. Note that the DataCamp schedule may change, with certain courses dropped/added.


## Engagement 10% {#engagement}

It is difficult to explicit codify what constitutes "an engaged student," so
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. That being said, here are multiple
pathways for you to stay engaged in this class:

* Asking and answering questions in class.
* Coming to office hours.
* Posting questions on Slack. Even better, responding to questions on Slack.
* Your peer evaluations for your mini-projects.


## Midterms 35%

* Two midterms during the semester
* Lower score weighted 15% and higher score weighted 20%.


## Five mini-projects 50%

* Mini-project 1: 5% - Groups of 2 selected by instructor.
* Mini-project 2: 7.5% - Groups of 2 selected by yourselves, must be a new partner.
* Mini-project 3: 10% - Groups of 2 selected by instructor, you'll be assigned a new partner.
* Mini-project 4: 12.5% - Groups of 2 selected by yourselves, must be a new partner.
* Mini-project 5: 15% - Groups of 2-3 freely chosen by yourselves.



<!--
## Weekly Problem Sets 10%

* Total of 10 problem sets: assigned during Tuesday labs, due the following week.
* Two lowest scores dropped. 
* The problem sets in this class should be viewed as low-stakes opportunities to
practice, instead of evaluative tools used by the instructor to assign grades.
**Each problem set is worth 1% of your final grade**.


## Weekly Problem Sets 20% {#problem_sets}

The problem sets in this class should be viewed as low-stakes opportunities to
practice, instead of evaluative tools used by the instructor to assign grades.

* ~~Basic structure~~: Updated below
    1. ~~You will be randomly assigned into pairs.~~
    1. ~~You will complete the problem set and submit it via GitHub pull request.~~
    1. ~~On the due date, I will pick a certain number of teams at random to present their findings.~~
    1. ~~You will have the option of updating your submissions.~~
* Sometimes problem sets will be individual, sometimes you will choose groups, sometimes you'll be randomly assigned into groups.
* Typical problem set timeline
    + Tuesday: problem set assigned
    + The following Tuesday 8:30am:
        + Submitted via a synchronized pull request by you/your team leader
        + Presentations (if applicable)
    + By Wednesday 9am: The TA will give feedback over GitHub. Do not commit/push any new changes until you've received the feedback.
    + By Thursday 8:30am: Revise/resubmit your work. There is no need to create a new pull request; the existing one will be updated.
    + By Monday: Albert will give his feedback and the grade. 
* Policy on collaboration:
    + While I encourage you to discuss problem sets with your peers, you must submit
your own answers and not simple rewordings of another's work.
    + As per the Amherst College Student Code of Conduct's statement on [intellectual responbisility and plagiarism](https://www.amherst.edu/offices/student-affairs/community-standards/intellectual-responsibility-and-plagiarism) **all collaborations must be explicitly acknowledged in your submissions**.
* Lowest two scores dropped.
* No extensions for problem sets will be granted. 


## DataCamp Assignments 5% {#datacamp}

* Assigned during Tuesday labs, due the following week.
* DataCamp is meant to be low stakes-practice, so the only thing that matters for your grade is whether you complete the course. So while things like the number of hints/solutions taken don't factor into your grade, it is important to make a good faith effort to answer these questions the best you can.
* While you may do them in advance if you are curious, it is most definitely not required. Note that the DataCamp schedule may change, with certain courses dropped/added.
* Jenny will talk more about DataCamp during Lab 2.


* Taking notes based on what you cover is not required, but please do so if you feel you will benefit. 
* I *expect* most people to take no more than 4 hours per DataCamp assignment.
* Please note retention of the material will not be perfect the first time through. The only way to really retain the material is via lots of practice/doing. For now, think of this as a introduction.


## Term Project 25% {#termproject}

See [Term Project](term_project.html) page.


## Three Midterms: 45%

* There will be three self-scheduled midterms, including one during finals week. See the [Midterms](midterms.html) page.
* Lowest score weighted 10%, middle score weighted 15%, and highest score weighted 20%.

There will be three midterms: two during the semester, one during finals week (dates posted under [Basic information](#basicinfo)).

* Two highest scores are weighted 15% each, lowest is weighted 10%. 
* All midterms are cumulative.
* There will be no make-up nor rescheduled midterms, except in the following
cases if documentation is provided (e.g. a dean's note):
    + serious illness or death in the family.
    + athletic commitments, religious obligations, and job interviews if
    prior notice is given. In such cases, rescheduled exams must be taken
    *after* the rest of the class.
* There will be no extra-credit work to improve midterm scores after the fact.


## Engagement 5% {#engagement}

It is difficult to explicit codify what constitutes "an engaged student," so
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. That being said, here are multiple
pathways for you to stay engaged in this class:

* Asking and answering question in class.
* Coming to office hours.
* Posting questions on Slack. Even better, responding to questions on Slack.
* Getting good peer evaluations for your term project.

It is difficult to explicit codify what constitutes "an engaged student," so 
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. Some examples of behavior counter to
this principle:

* Not participating in in-class exercises.
* Engaging so little with me, either in class or during office hours, that I
don't know what your voice sounds like.
* Submitting a problem set that has code or content that is copied from or is
only a slightly modified version of your peers' work.



## Policies

1. **Collaboration**: While I encourage you to work with your peers for problem
sets and labs, you must submit your own answers and not simple rewordings of
another's work. Furthermore, all collaborations must be explicitly acknowledged
in your submissions.
1. **Honor Code**: All your work must follow the [Smith College Academic Honor
Code Statement](https://www.smith.edu/sao/handbook/socialconduct/honorcode.php){target="_blank"};
in particular all external sources must be cited in your submissions.
1. **Problem sets**:
    + No extensions will be granted without a dean's note.
    + To receive full credit, you must show your work and explain your reasoning in your solutions. 
    + All written problem sets must be handed in at the start of lecture. No emailed submissions will be accepted; if you can't make it to class ask a classmate to turn it in for you. They must be stapled with the fringe/perf from any spiral notebook paper removed. 
1. **Midterms/quizzes**:
    + No make-up midterms will be allowed without a dean's note. 
    + Timestamps for all midterms will be strictly enforced.
1. **Grading**: I reserve the right to not discuss any grading issues in class and instead direct you to office hours. 

-->


***



# Accommodations {#accommodations}
 
Smith is committed to providing support services and reasonable accommodations to all students with disabilities. To request an accommodation, please register with the Disability Services Office at the beginning of the semester. To do so, call 413.585.2071 to arrange an appointment with Laura Rauscher, Director of Disability Services.



***


# Code of Conduct {#codeofconduct}

As the instructor and assistants for this course, we are committed to making
participation in this course a harassment-free experience for everyone,
regardless of level of experience, gender, gender identity and expression,
sexual orientation, disability, personal appearance, body size, race, ethnicity,
age, or religion. Examples of unacceptable behavior by participants in this
course include the use of sexual language or imagery, derogatory comments or
personal attacks, trolling, public or private harassment, insults, or other
unprofessional conduct.

As the instructor and assistants we have the right and responsibility to point
out and stop behavior that is not aligned to this Code of Conduct. Participants
who do not follow the Code of Conduct may be reprimanded for such behavior.
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the instructor.

**All students, the instructor, the lab instructor, and all assistants are
expected to adhere to this Code of Conduct in all settings for this course:
lectures, labs, office hours, tutoring hours, and over Slack.**

This Code of Conduct is adapted from the [Contributor
Covenant](http://contributor-covenant.org){target="_blank"}, version 1.0.0,
available [here](http://contributor-covenant.org/version/1/0/0/){target="_blank"}.


